/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWorldmapRouteImport } from './routes/_app/worldmap'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppRelationsRouteImport } from './routes/_app/relations'
import { Route as AppQuestsRouteImport } from './routes/_app/quests'
import { Route as AppProgressRouteImport } from './routes/_app/progress'
import { Route as AppPhilosophyRouteImport } from './routes/_app/philosophy'
import { Route as AppPermaRouteImport } from './routes/_app/perma'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppEcosystemRouteImport } from './routes/_app/ecosystem'
import { Route as AppDiaryRouteImport } from './routes/_app/diary'
import { Route as AppDesireRouteImport } from './routes/_app/desire'
import { Route as AppCampaignsRouteImport } from './routes/_app/campaigns'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldmapRoute = AppWorldmapRouteImport.update({
  id: '/worldmap',
  path: '/worldmap',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppRelationsRoute = AppRelationsRouteImport.update({
  id: '/relations',
  path: '/relations',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestsRoute = AppQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppPhilosophyRoute = AppPhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => AppRoute,
} as any)
const AppPermaRoute = AppPermaRouteImport.update({
  id: '/perma',
  path: '/perma',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppEcosystemRoute = AppEcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => AppRoute,
} as any)
const AppDiaryRoute = AppDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AppRoute,
} as any)
const AppDesireRoute = AppDesireRouteImport.update({
  id: '/desire',
  path: '/desire',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns': typeof AppCampaignsRoute
  '/desire': typeof AppDesireRoute
  '/diary': typeof AppDiaryRoute
  '/ecosystem': typeof AppEcosystemRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/map': typeof AppMapRoute
  '/perma': typeof AppPermaRoute
  '/philosophy': typeof AppPhilosophyRoute
  '/progress': typeof AppProgressRoute
  '/quests': typeof AppQuestsRoute
  '/relations': typeof AppRelationsRoute
  '/stats': typeof AppStatsRoute
  '/worldmap': typeof AppWorldmapRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/campaigns': typeof AppCampaignsRoute
  '/desire': typeof AppDesireRoute
  '/diary': typeof AppDiaryRoute
  '/ecosystem': typeof AppEcosystemRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/map': typeof AppMapRoute
  '/perma': typeof AppPermaRoute
  '/philosophy': typeof AppPhilosophyRoute
  '/progress': typeof AppProgressRoute
  '/quests': typeof AppQuestsRoute
  '/relations': typeof AppRelationsRoute
  '/stats': typeof AppStatsRoute
  '/worldmap': typeof AppWorldmapRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/desire': typeof AppDesireRoute
  '/_app/diary': typeof AppDiaryRoute
  '/_app/ecosystem': typeof AppEcosystemRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/map': typeof AppMapRoute
  '/_app/perma': typeof AppPermaRoute
  '/_app/philosophy': typeof AppPhilosophyRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/quests': typeof AppQuestsRoute
  '/_app/relations': typeof AppRelationsRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/worldmap': typeof AppWorldmapRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/campaigns'
    | '/desire'
    | '/diary'
    | '/ecosystem'
    | '/knowledge'
    | '/map'
    | '/perma'
    | '/philosophy'
    | '/progress'
    | '/quests'
    | '/relations'
    | '/stats'
    | '/worldmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/campaigns'
    | '/desire'
    | '/diary'
    | '/ecosystem'
    | '/knowledge'
    | '/map'
    | '/perma'
    | '/philosophy'
    | '/progress'
    | '/quests'
    | '/relations'
    | '/stats'
    | '/worldmap'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/_app/campaigns'
    | '/_app/desire'
    | '/_app/diary'
    | '/_app/ecosystem'
    | '/_app/knowledge'
    | '/_app/map'
    | '/_app/perma'
    | '/_app/philosophy'
    | '/_app/progress'
    | '/_app/quests'
    | '/_app/relations'
    | '/_app/stats'
    | '/_app/worldmap'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/worldmap': {
      id: '/_app/worldmap'
      path: '/worldmap'
      fullPath: '/worldmap'
      preLoaderRoute: typeof AppWorldmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relations': {
      id: '/_app/relations'
      path: '/relations'
      fullPath: '/relations'
      preLoaderRoute: typeof AppRelationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quests': {
      id: '/_app/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AppQuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/philosophy': {
      id: '/_app/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof AppPhilosophyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perma': {
      id: '/_app/perma'
      path: '/perma'
      fullPath: '/perma'
      preLoaderRoute: typeof AppPermaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecosystem': {
      id: '/_app/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof AppEcosystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diary': {
      id: '/_app/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof AppDiaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/desire': {
      id: '/_app/desire'
      path: '/desire'
      fullPath: '/desire'
      preLoaderRoute: typeof AppDesireRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppDesireRoute: typeof AppDesireRoute
  AppDiaryRoute: typeof AppDiaryRoute
  AppEcosystemRoute: typeof AppEcosystemRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMapRoute: typeof AppMapRoute
  AppPermaRoute: typeof AppPermaRoute
  AppPhilosophyRoute: typeof AppPhilosophyRoute
  AppProgressRoute: typeof AppProgressRoute
  AppQuestsRoute: typeof AppQuestsRoute
  AppRelationsRoute: typeof AppRelationsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppWorldmapRoute: typeof AppWorldmapRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRoute,
  AppDesireRoute: AppDesireRoute,
  AppDiaryRoute: AppDiaryRoute,
  AppEcosystemRoute: AppEcosystemRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMapRoute: AppMapRoute,
  AppPermaRoute: AppPermaRoute,
  AppPhilosophyRoute: AppPhilosophyRoute,
  AppProgressRoute: AppProgressRoute,
  AppQuestsRoute: AppQuestsRoute,
  AppRelationsRoute: AppRelationsRoute,
  AppStatsRoute: AppStatsRoute,
  AppWorldmapRoute: AppWorldmapRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
